name: monadology
version: "0.5"
author: Ashley Yakeley
copyright: (c) 2017-2025 Ashley Yakeley
license: BSD-2-Clause
license-file: LICENSE
maintainer: <ashley@semantic.org>
github: "AshleyYakeley/monadology"

category: Monads
synopsis: The best ideas in monad-related classes and types.
description: >
    Monadology is a collection of the best ideas in monad-related classes and types.

tested-with:
- "GHC == 9.8.4"
- "GHC == 9.10.1"

extra-doc-files:
- changelog.md

language: GHC2021
default-extensions:
- AllowAmbiguousTypes
- Arrows
- DataKinds
- DefaultSignatures
- DerivingStrategies
- FunctionalDependencies
- ImplicitParams
- NoImplicitPrelude
- LambdaCase
- OverloadedLabels
- OverloadedStrings
- PartialTypeSignatures
- PatternSynonyms
- QuantifiedConstraints
- RecordWildCards
- RecursiveDo
- RoleAnnotations
- NoStarIsType
- TemplateHaskell
- TypeAbstractions
- TypeFamilies
- TypeFamilyDependencies
- UndecidableInstances
- UndecidableSuperClasses
- ViewPatterns
ghc-options:
- -Weverything
- -Wno-missing-import-lists
- -Wno-missing-export-lists
- -Wno-unsafe
- -Wno-missing-safe-haskell-mode
- -Wno-missing-kind-signatures
- -Wno-partial-type-signatures
- -Wno-missing-role-annotations
- -Wno-monomorphism-restriction
- -Wno-missing-local-signatures
- -Wno-partial-fields
- -Wno-all-missed-specialisations # non-breaking
- -Wno-missed-specialisations # non-breaking

library:
    source-dirs: src
    dependencies:
    - base >= 4.19 && < 5
    - constraints >= 0.14
    - transformers >= 0.6
    - witness >= 0.7
    - invariant >= 0.6
    - type-rig >= 0.1
    exposed-modules:
    - Control.Monad.Ology.Specific.Result
    - Control.Monad.Ology.General.IO
    - Control.Monad.Ology.General.Function
    - Control.Monad.Ology.General.Cont
    - Control.Monad.Ology.General.Inner
    - Control.Monad.Ology.General.Outer
    - Control.Monad.Ology.General.Extract
    - Control.Monad.Ology.General.Identity
    - Control.Monad.Ology.General.Exception
    - Control.Monad.Ology.General.Throw
    - Control.Monad.Ology.General.Catch
    - Control.Monad.Ology.General.Coroutine
    - Control.Monad.Ology.General.Trans.Trans
    - Control.Monad.Ology.General.Trans.Constraint
    - Control.Monad.Ology.General.Trans.Hoist
    - Control.Monad.Ology.General.Trans.Tunnel
    - Control.Monad.Ology.General.Trans.Coerce
    - Control.Monad.Ology.General.Trans.Unlift
    - Control.Monad.Ology.General.Trans.AskUnlift
    - Control.Monad.Ology.General
    - Control.Monad.Ology.Specific.ComposeInner
    - Control.Monad.Ology.Specific.ComposeOuter
    - Control.Monad.Ology.Specific.IdentityT
    - Control.Monad.Ology.Specific.ComposeT
    - Control.Monad.Ology.Specific.MaybeT
    - Control.Monad.Ology.Specific.ExceptT
    - Control.Monad.Ology.Specific.ReaderT
    - Control.Monad.Ology.Specific.WriterT
    - Control.Monad.Ology.Specific.StateT
    - Control.Monad.Ology.Specific.ContT
    - Control.Monad.Ology.Specific.ReaderStateT
    - Control.Monad.Ology.Specific.StackT
    - Control.Monad.Ology.Specific.WithT
    - Control.Monad.Ology.Specific.ResultT
    - Control.Monad.Ology.Specific.StepT
    - Control.Monad.Ology.Specific.CoroutineT
    - Control.Monad.Ology.Specific.LifecycleT
    - Control.Monad.Ology.Data.Exn
    - Control.Monad.Ology.Data.Param
    - Control.Monad.Ology.Data.Prod
    - Control.Monad.Ology.Data.Ref
    - Control.Monad.Ology.Data
    - Control.Monad.Ology
    other-modules:
    - Control.Monad.Ology.General.Exception.Class
    - Import

tests:
    test:
        source-dirs: test
        dependencies:
        - base >= 4.19 && < 5
        - text >= 2.0
        - monadology
        - tasty >= 1.4
        - tasty-hunit >= 0.10
        main: Main.hs
        other-modules:
        - Useful
        - Exception
        - Compose
        - Coroutine
        - Lifecycle
        - Data
        ghc-options: -threaded
